<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-193VCU3" failures="3" tests="11" name="Contact page" time="87.835" errors="0" timestamp="2024-03-22T11:29:49 IST">
  <testcase classname="scripts.ContactPage_T_C" name="clientSideValidation" time="6.205"/>
  <testcase classname="scripts.ContactPage_T_C" name="serverSideValidationWithInvalidDetails" time="7.244"/>
  <testcase classname="scripts.ContactPage_T_C" name="serverSideValidationWithValidDetails" time="8.275"/>
  <testcase classname="scripts.ContactPage_T_C" name="validateErrorMessages" time="5.814">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at scripts.ContactPage_T_C.validateErrorMessages(ContactPage_T_C.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- validateErrorMessages -->
  <testcase classname="scripts.ContactPage_T_C" name="verifyConsole" time="3.388"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyMailId" time="3.63"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyMetaContent" time="4.492">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.util.List.get(int)&amp;quot; because the return value of &amp;quot;java.util.Map.get(Object)&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "java.util.Map.get(Object)" is null
at utilities.MetaFileHandler.readMetaContentFromExcel(MetaFileHandler.java:99)
at scripts.ContactPage_T_C.verifyMetaContent(ContactPage_T_C.java:142)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- verifyMetaContent -->
  <testcase classname="scripts.ContactPage_T_C" name="verifyNetworkStatus" time="5.533"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyProtocol" time="4.33"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyScrollButton" time="6.895">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at scripts.ContactPage_T_C.verifyScrollButton(ContactPage_T_C.java:116)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- verifyScrollButton -->
  <testcase classname="scripts.ContactPage_T_C" name="verifySubdomain" time="5.261"/>
</testsuite> <!-- Contact page -->
