<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-193VCU3" failures="2" tests="11" name="scripts.TermsPage_T_C" time="104.230" errors="0" timestamp="2024-05-03T16:48:30 IST" skipped="0">
  <testcase classname="scripts.TermsPage_T_C" name="verifyNetworkStatus" time="10.899"/>
  <testcase classname="scripts.TermsPage_T_C" name="verifyPageHeading" time="11.457"/>
  <testcase classname="scripts.TermsPage_T_C" name="verifyProtocol" time="8.914"/>
  <testcase classname="scripts.TermsPage_T_C" name="verifyHttpInPageSource" time="8.183">
    <failure message="The following asserts failed:
	expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at scripts.TermsPage_T_C.verifyHttpInPageSource(TermsPage_T_C.java:89)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
    </failure>
  </testcase> <!-- verifyHttpInPageSource -->
  <testcase classname="scripts.TermsPage_T_C" name="verifyTitleRepetition" time="7.489"/>
  <testcase classname="scripts.TermsPage_T_C" name="verifyStaticContent" time="9.226"/>
  <testcase classname="scripts.TermsPage_T_C" name="verifyConsole" time="13.566"/>
  <testcase classname="scripts.TermsPage_T_C" name="verifyMetaContent" time="8.367">
    <failure message="The following asserts failed:
	Your access to and use of our services are governed by our Terms of Use. Review our policies and obligations to ensure compliance. Yto access terms Review use of to services are governed by obligations to of Use. Review Terms policies and obligations to ensure expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Your access to and use of our services are governed by our Terms of Use. Review our policies and obligations to ensure compliance. Yto access terms Review use of to services are governed by obligations to of Use. Review Terms policies and obligations to ensure expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at scripts.TermsPage_T_C.verifyMetaContent(TermsPage_T_C.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
    </failure>
  </testcase> <!-- verifyMetaContent -->
  <testcase classname="scripts.TermsPage_T_C" name="verifyOgUrlRepetition" time="9.070"/>
  <testcase classname="scripts.TermsPage_T_C" name="verifyDescRepetition" time="7.418"/>
  <testcase classname="scripts.TermsPage_T_C" name="verifySubdomain" time="9.641"/>
</testsuite> <!-- scripts.TermsPage_T_C -->
